[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-none"
rustflags = ["-Cforce-frame-pointers=yes"]
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
