[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
color-eyre = "0.6.2"
owo-colors = "3.5.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
